### ISSUE TITLE
Split "One less new card for every forgotten review card." off?

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/SerenityNow#1]
Is there a reason for that feature (seemingly small piece of code) being in the same addon as the others? I'd like to understand how it works and whether it could be improved to fit some (maybe configurable) situation.

**Comment by lovac42** [comment]
It just increases the new card count so one less new card draws for that deck. I split it off here: https://github.com/lovac42/OneLessDraw

**Comment by aleksejrs** [comment]
Thank you.

Are the "#Ensure new cards comes last after review card" lines necessary? It seems like it should work with interleaving.

I guess it does not affect statistics?  It could make sense increasing the limit for today when I delete a failed card (maybe if it has a short interval).

**Comment by lovac42** [comment]
It shouldn't affect the stats and that line is needed. If new cards showed up first, there's no need to decrease the count. And a random mix of new/review will have unpredictable results, unless that's what you like.
