### ISSUE TITLE
Negative "cards to review" green number?

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/SerenityNow#2]
I haven't tried checking if that's caused by this add-on, but I've installed several add-ons at a time from the Anki repo yesterday, most of which are yours:
* serenityNow
* reflectOnMee
* cronholio (I haven't configured it)
* Cardistry (should only affect new cards)
* Button Colors Good Again (not yours and shouldn't affect anything)

In a small deck subtree (the other cards are filtered out), the number of cards left to review at the bottom under the card text was fluctuating. At the end, it became "-1" sometimes, and when it was "0", there were still review cards appearing.

I do have many other add-ons though.  I have been relying on the number of seconds left till the next In-Learning card, so I probably deleted any add-on that affected that.  The only one that might have intervened is `Limit_New_Cards_to_Less_Than_One.py` by Glutanimate, but it's for New cards.

**Comment by lovac42** [comment]
I don't know of those other addons, I mostly use my own codes and haven't seen what you are describing. Maybe a conflict with another addon? Try removing my addons and testing the others first.

**Comment by aleksejrs** [comment]
"Button Colors Good Again" should just be adding colors (CSS).

The other addons were installed earlier, and I haven't seen any negative numbers, despite reviewing with and without filtering.

**Comment by lovac42** [comment]
On second though, in serenityNow, change LOADBAL_DAYS to 0 from 3 and see if that fix the problem. This adds a few extra matured reviews from tomorrow's due for load balancing. So if you set total reviews to 200 and you only have 195, 5 extra matured cards will be pulled from tomorrow's dues. That could be the cause.

**Comment by aleksejrs** [comment]
That didn't help: there was still a review with an underlined green 0 (I should have taken a note of what the card was).
