### ISSUE TITLE
Multiple reviews of Review cards

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/SerenityNow#3]
What's this?  At least two review cards appeared again today, although I just answered them correctly:

```
Datum			Typ		Wertung	Intervall	Leichtigkeit	Zeit
11.11.2018 @ 18:22	Wiederholen	3	10,6 Mo.	250%	11,5s
11.11.2018 @ 18:22	Wiederholen	3	8,6 Mo.		250%	6,3s
25.07.2018 @ 10:42	Wiederholen	3	3,6 Mo.		250%	8,3s
11.06.2018 @ 22:27	Wiederholen	3	1,5 Mo.		250%	6,4s
```

**Comment by lovac42** [comment]
That's not enough info to go by... 2.1 2.0? Windows?
You really don't need this addon unless you have alot of over dues from vacation, so remove it if it's causing you problems.

**Comment by aleksejrs** [comment]
2.0.52, Debian GNU/Linux testing.

Although the problems are not yet big enough, and over a thousand cards is a lot for me to catch up with, I get it down significantly at least once in a month, and there are more interesting new add-ons to look at, so I uninstalled it for now.
